version: "3"

services:
  server:
    depends_on:
      - mariadb
    container_name: server
    restart: unless-stopped
    build: ./backend
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./backend:/usr/src/app

  mariadb:
    container_name: mariadb
    image: mariadb:10.2.38-bionic
    restart: always
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - ./database/volumes:/var/lib/mysql
