version: '3.1'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instaClondb
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: instaClonDB
      MYSQL_ROOT_PASSWORD: 123456
